[env:stable]
; recommended to pin to a version, see https://github.com/platformio/platform-espressif32/releases
; platform = espressif32 @ ^6.0.1
;platform = espressif32
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = esp32-c3-devkitm-1
framework = arduino
;board_build.partitions = partitions.csv
upload_speed = 921600

build_flags = 
    -std=gnu++17             ; Optimize for size
    -DCORE_DEBUG_LEVEL=5    
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps = 